#!/bin/bash
# Cleanup script for VMs affected by storage failure
# Don't run this
# Don't run this
# Don't run this
# Don't run this
# Don't run this

[[ $EUID -ne 0 ]] && printf "[ERROR]: Must run as root.\n" && exit 1
[[ $# -eq 0 ]] && printf >&2 "[ERROR]: Must pass in VMIDs as arguments.\n" && exit 1

if [[ "${*}" =~ [^0-9] ]]; then
    printf >&2 "[ERROR]: Non-digit characters found in arguments.\n"
    printf >&2 "Pass in only VMIDs for deletion.\n"
    exit 1
fi

declare -a DELETE=("$@")
printf "[WARNING]: Attempting to destroy VMs.\n"
printf "The following VMs with the IDs will be destroyed:\n"
printf -- "- %d\n" "${DELETE[@]}"

declare -l CHOICE
read -r -p "Continue? [y/N]" CHOICE

if [[ ${CHOICE:-n} == n* || "${CHOICE:-n}" != y*  ]]; then
    printf "Exiting.\n"
    exit 0
fi

for vmid in "${DELETE[@]}"; do
    if [[ $(sudo qm status "$vmid") == "status: running" ]]; then
        qm stop "$vmid"
    fi
    printf "Destroying VMID: %d...\n" "$vmid"
    qm destroy "$vmid" || {
        printf >&2 '[ERROR]: Failed to destroy VM with ID: %d\n' "$vmid"
        continue
    }
    printf "VM successfully destroyed.\n"
done
