#!/bin/bash

declare EN_DASH="–"
declare OPEN_QUOTE='“'
declare CLOSE_QUOTE='”'
declare APOSTRAPHE="’"
declare ELLIPSES="…"

declare -a FILES
read -r -d '' -a FILES < <(find ./src/ -name 'u*' -type f -name '*.md' -o -name '*.txt')
printf "File: %s\n" "${FILES[@]}"

sed -iE \
    -e "s/(${OPEN_QUOTE}|${CLOSE_QUOTE})/\"/g" \
    -e "s/$EN_DASH/-/g" \
    -e "s/$APOSTRAPHE/'/g" \
    -e "s/$ELLIPSES/.../g" \
    "${FILES[@]}"

# perl -CSDA -Mutf8 -Mopen=:std,:encoding\(UTF-8\) -pi -e '
#     use charnames ":full";  # Allow using Unicode names
#     s/\N{LEFT DOUBLE QUOTATION MARK}|\N{RIGHT DOUBLE QUOTATION MARK}/"/g;
#     s/\N{EN DASH}/-/g;
#     s/\N{RIGHT SINGLE QUOTATION MARK}/'\''/g;
# ' "${FILES[@]}"

