#!/bin/bash
# Disable local access to all social media platforms.  
# TODO(unlock): Add code to remove /etc/hosts entries

declare HOSTS_FILE="/etc/hosts"
declare -a SITES=(
    "x.com"
    "reddit.com"
    "facebook.com"
)
declare -i UNLOCK=0

fatal(){ printf >&2 '[FATAL ERROR]: %s\n' "$*" && exit 1; }
err(){ printf >&2 '[ERROR]: %s\n' "$*" && exit 1; }
info(){ printf '[INFO]: %s\n' "$*"; }

[[ $EUID -ne 0 ]] && fatal "Must run as root."

block-access(){
    local entry
    [[ -z $1 ]] && err "No argument passed!" && return 1
    entry="127.0.0.1 $1 www.$1"
    info "Entry for $1: '$entry'"
    if grep -qi "$entry" "$HOSTS_FILE"; then
        info "Entry already exists"
        return 0
    fi
    printf "%s\n" "$entry" >> "$HOSTS_FILE"
    # sed -i '$a '"$entry" "$HOSTS_FILE" || {
    #     err "Couldn't add entry for $1"
    #     return 1
    # }
}

unblock-access() {
    local entry
    if [[ -z $1 ]]; then
        err "No argument passed to unblock-access"
    fi
    printf "Unblocking access for %s\n" "$1"
    entry="127\.0\.0\.1 $1 www\.$1"
    sed -i "/$entry/d" "$HOSTS_FILE" || {
        err "Couldn't unblock access to $1"
        return 1
    }
}

while [[ -n $1 && $1 =~ ^- && ! $1 == '--' ]]; do
    case $1 in
        -u|--unlock)
            UNLOCK=1
            shift
            ;;
        -f|--hosts-file)
            if [[ -n $2 && ! $2 =~ ^- ]]; then
                shift
                [[ -f $1 ]] || fatal "Hosts file given to '-f' ($1) does not exist"
                HOSTS_FILE=$1
            else
                fatal "Missing or invalid argument to -f / --hosts-file"
            fi
            shift;
            ;;
        *)
            fatal "Bad argument: $1"
            ;;
    esac
done
[[ $1 == '--' ]] && shift

if [[ $UNLOCK -gt 0 ]]; then
    printf "Unblocking sites...\n"
    for site in "${SITES[@]}"; do
        unblock-access "$site" || {
            err "Failed to unblock access to $site"
        }
    done
else
    printf "LOCKING IN...\n"
    for site in "${SITES[@]}"; do
        info "Blocking site: $site"
        block-access "$site" || {
            err "Failed to block access to $site"
        }
    done
fi


