#!/bin/bash

parse-ansible-inventory(){
    local -a ENTRIES=()
    IFS=$'\n' read -r -d $'\0' -a ENTRIES < <(
        perl -ne 'print "$1\n" if m/ansible_host=(\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})/' "$1"
    )
    printf "Entries: %s\n" "${ENTRIES[@]}"
    IPS=("${IPS[@]}" "${ENTRIES}")
}



parse-ssh-config(){
    local -a ENTRIES=()
    SSH_CONFIG_FILE="$1"
    IFS=$'\n' read -r -d $'\0' -a ENTRIES < <(
        perl -ne 'print "$1\n" if m/^\s*Hostname\s*(\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})/' "$SSH_CONFIG_FILE"
    )
    printf "Entries: %s \n" "${ENTRIES[@]}"
}

parse-ssh-config ~/.ssh/config
parse-ansible-inventory ./hosts.ini

# [[ -n $1 ]] && parse-ansible-inventory "$1" || printf >&2 "No arguments given."

#
#
