#!/bin/bash

declare INVENTORY_FILE
declare SSH_CONFIG_FILE

parse-ansible-inventory(){
    local -a ENTRIES=()
    IFS=$'\n' read -r -d $'\0' -a ENTRIES < <(
        perl -ne 'print "$1\n" if m/ansible_host=(\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})/' "$1"
    )
    printf "Entries: %s\n" "${ENTRIES[@]}"
    IPS=("${IPS[@]}" "${ENTRIES}")
}



parse-ssh-config(){
    local -a ENTRIES=()
    SSH_CONFIG_FILE="$1"
    IFS=$'\n' read -r -d $'\0' -a ENTRIES < <(
        perl -ne 'print "$1\n" if m/^\s*Hostname\s*(\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})/' "$SSH_CONFIG_FILE"
    )
    printf "Entries: %s \n" "${ENTRIES[@]}"
}

err() {
    printf >&2 '[ERROR]: %s\n' "$*"
}

while [[ -n $1 && $1 =~ ^- ]]; do
    case "$1" in
        -i|--inventory-file)
            if [[ -n $2 && -f $2 ]]; then
                shift
                INVENTORY_FILE="$1"
            else
                err "Bad argument to -i/--inventory-file: $1"
                exit 1
            fi
            shift
            ;;
        -s|--ssh-config-file)
            if [[ -n $2 && -f $2 ]]; then
                shift
                SSH_CONFIG_FILE="$1"
            else
                err "Bad argument to -s/--ssh-config-file: $1"
                exit 1
            fi
            shift
            ;;
        *)
            err "Invalid argument: $1"
            exit 1
            ;;
    esac
done

parse-ansible-inv "$INVENTORY_FILE"
parse-ssh-config "$SSH_CONFIG_FILE"
