#!/bin/bash

# SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# printf "Script dir: %s\n" "$SCRIPT_DIR"

declare RESOURCES_FILE='./src/resources.md'
declare SEARCH_DIR="./src"
declare FILE_PATTERN="*.md"

declare -a FILES
IFS=$'\n' read -r -d '' -a FILES < <(find "$SEARCH_DIR" -maxdepth 1 -mindepth 1 -name "$FILE_PATTERN")

# Debug the files array
# for FILE in "${FILES[@]}"; do
#     printf "File: %s\n" "$FILE"
# done

# truncate file
: > "$RESOURCES_FILE"

debug() {
    printf "[ \033[33mDEBUG\033[0m ]: "
    printf "%s\n" "$*"
}

pull-links() {
    local -i COUNT_MD_LINKS=0
    local -i COUNT_REG_LINKS=0
    local -i COUNT_UF_LINKS=0
    for FILE in "${FILES[@]}"; do
        local UNIT=
        [[ "$FILE" == *resources.md ]] && continue  

        printf "File: %s\n" "$FILE"
        declare -a RESOURCES

        IFS=$'\n' read -r -d '' -a RESOURCES < <(
            grep -i -E '\<https://' "$FILE" |
                # grep -v -E '(img)? ?src=|discord\.(gg|com)|user-attachments|.*\.png'
                grep -v -E '(img)? ?src=|discord\.(gg|com)|user-attachments'
        )

        for RESOURCE in "${RESOURCES[@]}"; do
            local RESOURCE
            [[ $FILE =~ .*u([0-9]+).*\.md ]] && UNIT="${BASH_REMATCH[1]}"
            [[ -n $UNIT ]] && printf "\033[32mUNIT NUMBER: %s\n \033[0m" "${UNIT}"

            # extract the link from the line
            MARKDOWN_LINK="$(printf "%s" "$RESOURCE" | sed -E -e 's/.*(\[.*\]\(.*\)).*/\1/')" 
            # -e 's/.*(\<.*\>)/\1/' )"

            debug "$MARKDOWN_LINK"
            if [[ $MARKDOWN_LINK =~ .*(<.*>).* ]]; then
                # link is formatted as: <http://example.com>
                debug "Regular link detected: ${BASH_REMATCH[1]}"
                MARKDOWN_LINK="${BASH_REMATCH[1]}"
                COUNT_REG_LINKS+=1
            elif [[ $MARKDOWN_LINK =~ .*[^[\<\(](https://[^ \)]+).* ]]; then
                # link is unformatted: http://example.com
                debug "Unformatted link detected: ${BASH_REMATCH[1]}"
                MARKDOWN_LINK="${BASH_REMATCH[1]}"
                continue
                COUNT_UF_LINKS+=1
            else
                # link is formatted as: [Link](http://example.com)
                COUNT_MD_LINKS+=1
            fi

            if printf "%s" "$MARKDOWN_LINK" | grep -i 'professionallinuxusersgroup'; then
                printf "Found GH link in unit %s: %s" "$UNIT" "$MARKDOWN_LINK"
            fi

            if ! grep -qi "$MARKDOWN_LINK" "$RESOURCES_FILE"; then

                [[ -z $UNIT ]] && sed -i "/^## Misc$/a - $MARKDOWN_LINK" "$RESOURCES_FILE"
                [[ -n $UNIT ]] && sed -i "/^## Unit $UNIT\>/a - $MARKDOWN_LINK" "$RESOURCES_FILE"

                # DEBUG: insert filename with link
                # [[ -z $UNIT ]] && sed -i "/^## Misc$/a $(basename "$FILE"): $MARKDOWN_LINK" "$RESOURCES_FILE"
                # [[ -n $UNIT ]] && sed -i "/^## Unit $UNIT\>/a $(basename "$FILE"): $MARKDOWN_LINK" "$RESOURCES_FILE"

            else
                debug "Link found, skipping."
            fi

        done

    done

    TOTAL_LINK_COUNT=$(( COUNT_MD_LINKS + COUNT_UF_LINKS + COUNT_REG_LINKS ))
    printf "\nREPORT:\n- Markdown Links\t%s\n- Regular Links\t\t%s\n- Unformatted Links\t%s\n\nTotal Links: %s\n" "$COUNT_MD_LINKS" "$COUNT_REG_LINKS" "$COUNT_UF_LINKS" "$TOTAL_LINK_COUNT"
}

format-resources() {
    cat <<- EOF >> "$RESOURCES_FILE"
	<div class="flex-container">
	        <img src="https://github.com/ProfessionalLinuxUsersGroup/img/blob/main/Assets/Logos/ProLUG_Round_Transparent_LOGO.png?raw=true" width="64" height="64"></img>
	    <p>
	        <h1>Course Resources</h1>
	    </p>
	</div>
	This is a comprehensive list of all external resources used in this course.

	EOF

    for i in {1..16}; do
        if ! grep -qi -E "^## Unit ${i}$" "$RESOURCES_FILE"; then
            printf "## Unit %s\n\n" "$i" >> "$RESOURCES_FILE"
        fi
    done

    if ! grep -qi -E "^## Misc$" "$RESOURCES_FILE"; then
        printf "## Misc\n" >> $RESOURCES_FILE
    fi
}

format-resources
pull-links

: ' Example CI/CD integration 
      - name: Generate resources.md dynamically
        run: ./scripts/generate_resources.sh

      - name: Check for uncommitted changes
        run: |
          git diff --exit-code || (echo "::error::resources.md is outdated. Run the script and commit it." && exit 1)
'
