#!/bin/bash
# Basic script used to send a payload to a webhook URL.  
# Use `-m` to specify message, use `-f` to specify a file containing the
# webhook URL. 

declare MESSAGE
declare WEBHOOK_URL
declare WEBHOOK_URL_FILE

while [[ -n $1 && $1 =~ ^- && ! $1 == '--' ]]; do
    case "$1" in
        -m|--message)
            [[ -n $2 && ! $2 =~ ^- ]] && shift && MESSAGE="$1"
            shift
            ;;
        -f|--webhook-url-file)
            [[ -n $2 && ! $2 =~ ^- ]] && shift && WEBHOOK_URL_FILE="$1"
            if [[ -f $WEBHOOK_URL_FILE ]]; then
                WEBHOOK_URL="$(head -n 1 "$WEBHOOK_URL_FILE")"
            else
                printf >&2 '[ERROR]: No such file: %s\n' "$WEBHOOK_URL_FILE"
                exit 1
            fi
            shift
            ;;
        *) 
            printf >&2 '[ERROR]: Unknown argument: %s\n' "$1"
            exit 1
            ;;
    esac
    :
done

report-webhook(){
    local PAYLOAD='{"content":"'$MESSAGE'"}'

    curl -X POST \
        -H "Content-Type: application/json" \
        -d "$PAYLOAD" "$WEBHOOK_URL" || {
            printf >&2 '[ERROR]: Failed to send message to webhook!\n'
            return 1
        }
}

if [[ -n $MESSAGE && -n $WEBHOOK_URL ]]; then
    report-webhook
else
    printf >&2 '[ERROR]: Missing message or webhook URL!\n'
    exit 1
fi

