#!/bin/bash

# 2025-08-21

declare OS
declare SAMBA_DIR='/srv/samba/share1'
declare SAMBA_CONFIG='/etc/samba/smb.conf'
declare INSTALL


grep -qi 'debian' /etc/*release && OS=debian
grep -qi 'redhat' /etc/*release && OS=redhat

if [[ -n $1 ]]; then
    case "${1,,}" in
        client)
            INSTALL=client
            shift;
            ;;
        server)
            INSTALL=server
            shift;
            ;;
        *)
            printf >&2 "Unknown argument: %s\nExiting.\n" "$1"
            exit 1
            ;;
    esac
else
    printf >&2 "%s [ERROR]: Either 'server' or 'client' must be specified as the first argument.\n" "$(date '+%F %T')"
    exit 1
fi

install-server-redhat() {
    sudo dnf install -y samba || {
        printf >&2 "%s [ERROR]: Failed to install the samba package!\n" "$(date '+%F %T')"
        return 1
    }
    sudo mkdir -p -m0755 "$SAMBA_DIR" || {
        printf >&2 "%s [ERROR]: Failed to create the samba directory: %s\n" "$(date '+%F %T')" "$SAMBA_DIR"
        return 1
    }
    [[ -f "$SAMBA_CONFIG" ]] || {
        printf >&2 "%s [ERROR]: Samba config could not be located at: %s\n" "$(date '+%F %T')" "$SAMBA_CONFIG"
        return 1
    }
    return 0
}


install-server-debian() {
    sudo apt-get install -y samba || {
        printf >&2 "%s [ERROR]: Failed to install the samba package!\n" "$(date '+%F %T')"
        return 1
    }
    sudo mkdir -p -m0755 "$SAMBA_DIR" || {
        printf >&2 "%s [ERROR]: Failed to create the samba directory: %s\n" "$(date '+%F %T')" "$SAMBA_DIR"
        return 1
    }
    [[ -f "$SAMBA_CONFIG" ]] || {
        printf >&2 "%s [ERROR]: Samba config could not be located at: %s\n" "$(date '+%F %T')" "$SAMBA_CONFIG"
        return 1
    }
    return 0
}

install-client-redhat() {
    sudo dnf install -y cifs-utils || {
        printf >&2 "%s [ERROR]: Failed to install the cifs-utils package!\n" "$(date '+%F %T')"
        return 1
    }
    return 0
}

install-client-debian() {
    sudo apt-get install -y cifs-utils || {
        printf >&2 "%s [ERROR]: Failed to install the cifs-utils package!\n" "$(date '+%F %T')"
        return 1
    }
    return 0
}

if [[ $INSTALL == 'client' ]]; then
    "install-client-${OS}"
else
    "install-server-${OS}"
fi

