#!/bin/bash

# Translate HTML Headers to Markdown
# - First 6 lines of each markdown file consist of the HTML header
# - Remove the first 3
# - Strip the header title from the H1 on line 4
# - Strip lines 5 and 6

for f in "$@"; do
    perl -pi -e '
        s/^.*\n// if ( $. < 4 );
        s/^.*\n// if ( $. > 4 and $. < 7 );
        s/^.*<h1>(.*)<\/h1>$/# $1/ if ( $. == 4 )' "$f"
done

for f in "$@"; do
    # perl -pi -e 's/^(# Unit (\d+) (Worksheet|Lab|Intro)).*/$1/' "$f"
    perl -pi -e 's/^\s*<h1>(.*)<\/h1>.*$/# $1/' lac/u*intro.md
done


