#!/bin/bash

# 5. Cross Toolchain Setup
# Installs the cross compilation toolchain that will be used to build the
# temporary tools in Chapter 6 of LFS.  
# This builds the tools in $LFS/tools, which will not be used for the final LFS
# system. These tools are used for the temp system that will be used to build the 
# final LFS system.


