#!/bin/bash
# Pre-install setup script used to configure the environment for the LFS build
# process. This script creates necessary directories, sets up the LFS user, and ensures
# that the environment variables are properly sourced.

if [[ $EUID -ne 0 ]]; then
    printf >&2 "ERROR: Run as root.\n"
    exit 1
fi

if [[ -f ./env-vars ]]; then
    source ./env-vars
else
    printf >&2 "ERROR: env-vars file not found. Please create it with the necessary environment variables."
    exit 1
fi

declare -xr LFS_USER="lfs"

create-dirs(){

    cd "$LFS" || {
        printf >&2 "ERROR: Failed to change directory to %s\n" "$LFS"
        exit 1
    }
    mkdir -pv $LFS/{etc,var} $LFS/usr/{bin,lib,sbin}

    for dir in {bin,lib,sbin}; do
        printf "Linking %s to %s\n" "usr/$dir" "$LFS/$dir"
        ln -sv "usr/$dir" "$LFS/$dir"
    done

    case "$(uname -m)" in
        x86_64)
            mkdir -pv "$LFS/lib64";;
    esac
    mkdir -pv "$LFS/tools"

}

setup-lfs-user(){
    groupadd "$LFS_USER"
    useradd -s /bin/bash -g "$LFS_USER" -m  -k /dev/null "$LFS_USER" || {
        printf >&2 'ERROR: Failed to add user %s\n' "$LFS_USER"
    }
    chown -v "$LFS_USER" $LFS/{usr{,/*},var,etc,tools}

    printf "LFS user created with username: %s\n" "$LFS_USER"

    cat > /home/$LFS_USER/.bash_profile << 'EOF'
exec env -i HOME="$HOME" TERM="$TERM" PS1='\u:\w\$ ' /bin/bash
EOF

    cat > /home/$LFS_USER/.bashrc << 'EOF'
set +h
umask 022
LFS=/mnt/lfs
LC_ALL=POSIX
LFS_TGT=$(uname -m)-lfs-linux-gnu
PATH=/usr/bin
if [ ! -L /bin ]; then PATH=/bin:$PATH; fi
PATH=$LFS/tools/bin:$PATH
CONFIG_SITE=$LFS/usr/share/config.site
export LFS LC_ALL LFS_TGT PATH CONFIG_SITE
export MAKEFLAGS=-j$(nproc)
EOF

    [[ ! -e /etc/bash.bashrc ]] || mv -v /etc/bash.bashrc /etc/bash.bashrc.NOUSE

}

create-dirs
setup-lfs-user

printf "IMPORTANT: Please make sure to set a password for the %s user.\n" "$LFS_USER"
printf "Run 'passwd %s'\n" "$LFS_USER"
printf "Make sure to switch to the LFS user for the rest of the setup process.\n" 

