#!/bin/bash
# shellcheck disable=SC2016
declare -r TARGET_DISK="/dev/sdb"
declare -r MOUNT_POINT="/mnt/lfs"

if [[ $EUID -ne 0 ]]; then
    printf >&2 'ERROR: Run as root.\n'
    exit 1
fi

declare selection
read -r -p "WARNING: This is a destructive operation. It will overwrite the disk: $TARGET_DISK. Continue? [y/N]" selection
case $selection in
    n|N|n*|N*)
        printf "Aborting...\n"
        exit 0
esac

partition-disk(){
    printf "Running the script through SFDISK now...\n"

    { 
        sfdisk "$TARGET_DISK" << 'EOF'
# Partition table type
label: gpt
unit: sectors
first-lba: 2048

# BIOS boot partition
# This `type` specifies a BIOS Boot Partition
size=1M, type=21686148-6449-6E6D-744E-6574626F6F74, name="BIOS_Boot"

# 1. /boot (EFI System Partition) - 1GB
# type=U is the shortcut for EFI System
size=1G, type=U, name="EFI_System"

# 2. Swap - 4GB
# type=S is the shortcut for Linux Swap
size=4G, type=S, name="Linux_Swap"

# 3. / (Root) - Remainder of disk
# type=L is the shortcut for Linux Filesystem
type=L, name="Linux_Root"
EOF
    } || {
        printf >&2 '[ERROR]: Failed to run script through SFDISK.\n'
        return 1
    }

    printf 'Successfully ran script through SFDISK.\n'
    fdisk -l "$TARGET_DISK"
    return 0
}


format-disk(){
    printf "Formatting disk partitions for disk %s...\n" "$TARGET_DISK"
    # local BIOS_PARTITION="${TARGET_DISK}1"
    local EFI_PARTITION="${TARGET_DISK}2"
    local SWAP_PARTITION="${TARGET_DISK}3"
    local ROOT_PARTITION="${TARGET_DISK}4"

    printf "Formatting EFI system partition (FAT32)...\n"
    mkfs.vfat -f32 "$EFI_PARTITION" || {
        printf >&2 '[ERROR]: Failed to format EFI System Partition\n'
        return 1
    }

    printf "Formatting SWAP partition as SWAP...\n"
    mkswap "$SWAP_PARTITION" || { 
        printf >&2 '[ERROR]: Failed to format SWAP partition.\n'
        return 1
    }

    printf "Formatting Root Filesystem Partition as EXT4...\n"
    mkfs.ext4 "$ROOT_PARTITION" || {
        printf >&2 '[ERROR]: Failed to format root filesystem partition as EXT4: %s\n' "$ROOT_PARTITION"
        return 1
    }
}

mount-partition(){
    local rootfs_uuid
    rootfs_uuid="$(lsblk -o UUID "${TARGET_DISK}4" | tail -n 1)"
    local fstab_entry="/dev/disk/by-uuid/$rootfs_uuid $MOUNT_POINT ext4 defaults 0 0"

    { swapon "${TARGET_DISK}3" && swapon; } || { 
        printf >&2 '[ERROR]: Failed to enable SWAP for %s\n' "${MOUNT_POINT}3"
    }

    if ! [[ -d $MOUNT_POINT ]]; then
        mkdir -p "$MOUNT_POINT" || {
            printf >&2 '[ERROR]: Failed to make mount point: %s\n' "$MOUNT_POINT"
            return 1
        }
    fi

    mount -t ext4 "${TARGET_DISK}4" "$MOUNT_POINT" || {
        printf >&2 '[ERROR]: Failed to mount disk %s to %s\n' "${TARGET_DISK}4" "$MOUNT_POINT"
        return 1
    }

    chown root:root "$MOUNT_POINT" || { 
        printf >&2 '[ERROR]: Failed to change ownership for mount point %s\n' "$MOUNT_POINT"
        return 1
    }

    chmod 755 "$MOUNT_POINT" || {
        printf >&2 '[ERROR]: Failed to change permissions for mount point %s\n' "$MOUNT_POINT"
        return 1
    }

    printf "Adding /etc/fstab entry for persistent mounting...\n"
    tee -a /etc/fstab <<< "$fstab_entry" || {
        printf >&2 '[ERROR]: Failed to add /etc/fstab entry: %s\n' "$fstab_entry"
        return 1
    }

    printf "fstab entry added. Attempting remount...\n"
    mount -a || {
        printf >&2 '[ERROR]: Failed to remount with /etc/fstab\n'
        return 1
    }

}

partition-disk || {
    printf >&2 '[ERROR]: Problem while partitioning disk.\n'
    exit 1
}

format-disk || {
    printf >&2 '[ERROR]: Problem while formatting disk partitions.\n'
    exit 1
}

mount-disk || {
    printf >&2 '[ERROR]: Problem while mounting rootfs disk partition.\n'
    exit 1
}

