#!/usr/bin/bash
set -euo pipefail
IFS=$'\n\t'

LOGFILE="/home/testbox/backups/caddy/caddy-settings-$(date +%Y%m%d%H%M%S).log"
OUTDIR="/home/testbox/backups/caddy"

rsync_exit_status=0

sudo -E RSYNC_RSH="ssh -F /home/testbox/.ssh/config" rsync --info=progress2 --rsync-path="sudo rsync" --human-readable -azvvt -c \
    --log-file="$LOGFILE" \
    --exclude="*.iso" \
    10.10.10.2:/etc/caddy \
    10.10.10.2:/etc/wireguard \
    "$OUTDIR" || rsync_exit_status=$?


if [ $rsync_exit_status -eq 0 ]; then
    # Backups are sucessful
    curl -d "Backups were sucessful for caddy RC:${rsync_exit_status}" ntfy.sh/testbox
else
    # Backups were not sucessful
    curl -d "Backups failed for caddy RC:${rsync_exit_status}" ntfy.sh/testbox
fi
