#!/bin/bash
declare BUILD_DIR="$HOME/book-lac"
declare BOOK_LINK
declare REMOTE="origin"
declare BRANCH="main"

err() {
    [[ $# -gt 0 ]] && {
        local ERR="[ \033[31m ERROR \033[0m ]: "
        printf >&2 "%s%s\n" "${ERR}" "$@"
    }
}

warn() {
    [[ $# -gt 0 ]] && {
        local WARNING="[ \033[33m WARNING \033[0m ]: "
        printf "%s%s\n" "${WARNING}" "$@"
    }
}


pull-upstream(){
    cd "${BUILD_DIR}" || {
        err "Failed to change directory to ${BUILD_DIR}!" && return 1
    }
    git switch -c "${BRANCH}" || {
        err "Failed to switch to branch: $BRANCH" && return 1
    } 
    if ! { [[ -n $REMOTE ]] && git pull "${REMOTE}" "${BRANCH}"; }; then
        err "Failed to pull from remote repository: ${REMOTE}! Is the git remote set up?" && return 1
    fi
    return 0
}

while [[ -n $1 ]]; do
    case $1 in
         -d|--directory)
            if [[ -n $2 ]] && [[ ! $2 =~ ^- ]]; then
                printf "Using %s as build directory.\n" "$2"
                shift;
                BUILD_DIR=$1
            else
                err "The -d option was given but no directory was specified. Using default ($BUILD_DIR)."
            fi
            shift;
            ;;

       -p|--pull)
            if [[ -n $2 ]] && [[ ! $2 =~ ^- ]]; then
                shift;
                printf "Pulling from remote: %s\n" "$1"
                REMOTE=$1
            fi
            printf "Pulling changes from %s...\n" "${REMOTE:=origin}"
            pull-upstream || {
                printf "Failed to update repo from upstream. Exiting.\n" && exit 1
            }
            shift;
            ;;

        -b|--branch)
            if [[ -n $2 ]] && [[ ! $2 =~ ^- ]]; then
                printf "Using %s as the branch.\n" "${BRANCH}"
                shift;
                BRANCH=$1
            fi
            printf "Pulling from branch: %s\n" "${BRANCH:=main}"
            shift;
            ;;

        *)
            warn "Unknown option: $1 - Discarding.\n"
            shift;
            ;;
    esac
done

ACTIVE=$(sudo systemctl is-active apache2)
if [[ ${ACTIVE,,} != 'active' ]]; then
    warn "Apache WebServer is not active! Attempting to start apache2..."
    sudo systemctl start apache2 || {
        err "Failed to start Apache WebServer." && exit 1
    }
fi

build() {
    { [[ -d "${BUILD_DIR}" ]] && cd "${BUILD_DIR}"; } || {
        err "No ${BUILD_DIR} directory!" && return 1
    }

    { [[ -f ~/.cargo/bin/mdbook ]] && ~/.cargo/bin/mdbook build -d /var/www/html; } || {
        err "Failed to build book using mdbook!" && return 1
    }
}

if ! build; then
    err "Failed to build book.\n" && exit 1
fi

BOOK_LINK="http://$(hostname -I | awk '{print $1}' | tr -d ' ')"
printf "Run the following command to verify:\ncurl %s\n" "${BOOK_LINK}"
printf "Or, visit the following link: %s\n" "${BOOK_LINK}"

