#!/bin/bash
declare BUILD_DIR
declare BOOK_LINK

err() {
    [[ $# -gt 0 ]] && {
        local ERR="[ \033[31m ERROR \033[0m ]: "
        printf >&2 "%s%s\n" "${ERR}" "$@"
    }
}

pull-upstream(){
    cd ~/lac || {
        err "Failed to change directory to ~/lac!" && return 1
    }
    git pull upstream main || {
        err "Failed to pull from upstream!" && return 1
    }
    return 0
}

while [[ -n $1 ]]; do
    case $1 in
        -p|--pull)
            printf "Pulling changes from upstream\n"
            pull-upstream || {
                printf "Failed to update repo from upstream. Exiting.\n" && exit 1
            }
            shift;
            ;;
        -d|--directory)
            if [[ -n $2 ]]; then
                printf "Using %s as build directory.\n" "$2"
            else
                err "The -d option given but no directory was specified. Using default."
            fi
            shift;
            BUILD_DIR=$1
            shift;
            ;;
        *)
            printf "Unknown option. Discarding.\n"
            shift;
            ;;
    esac
done

: "${BUILD_DIR:=$HOME/book-lac}"


ACTIVE=$(sudo systemctl is-active apache2)
if [[ ${ACTIVE,,} != 'active' ]]; then
    err "Apache WebServer is not active!"
    exit 1
fi

build() {

    { [[ -d "${BUILD_DIR}" ]] && cd "${BUILD_DIR}"; } || {
        err "No ${BUILD_DIR} directory!" && return 1
    }

    { [[ -f ~/.cargo/bin/mdbook ]] && ~/.cargo/bin/mdbook build -d /var/www/html; } || {
        err "Failed to build book using mdbook!" && return 1
    }
}

if ! build; then
    err "Failed to build book.\n" && exit 1
fi

BOOK_LINK="http://$(hostname -I | awk '{print $1}' | tr -d ' ')"
printf "Run the following command to verify:\ncurl %s\n" "${BOOK_LINK}"
printf "Or, visit the following link: %s\n" "${BOOK_LINK}"

