#!/bin/bash

[ -n "$1" ] && IP=$1
: "${IP:="$(hostname -I | awk '{print $1}' | tr -d ' ')"}"


check-service() {
    if pgrep -i "$1"; then
        return 0
    else
        return 1
    fi
}

declare -A PORTS

PORTS=(
    [Node_exporter]=9100 
    [Grafana]=3000
    [Loki]=3100
    [Promtail]=9080
    [Prometheus]=9090
    [InfluxDB2]=8086
)


printf "\nPorts:\n"
for idx in "${!PORTS[@]}"; do
    printf "\t%s:\t%s\n" "$idx" "${PORTS[$idx]}";
    if [[ "$idx" =~ Prometheus|Grafana|Promtail ]]; then
        if check-service "$idx"; then
            printf "\t- %s link: %s\n" "$idx" "http://${IP}:${PORTS[$idx]}"
        else
            printf "\tThe %s service is not running on this node.\n" "$idx"
            printf "\tThe link will be http://<host-ip>:%s\n" "${PORTS[$idx]}"
        fi
    elif [[ $idx =~ Loki ]] && check-service "$idx"; then
        printf "\t- %s Ready link: %s/ready\n" "$idx" "http://${IP}:${PORTS[$idx]}"
    fi

done

printf '\n'
printf "Remember, you can check what is using a port with 'lsof'\n"
printf "Ex: sudo lsof -i :9096\n\n"

printf "If you need to query Loki manually, use curl:\n
    curl http://%s/loki/api/v1/query_range \\ 
        --data-urlencode 'query={job=\"all\"}' \\ 
        --data-urlencode 'limit=10'\n
" "${IP}:${PORTS[Loki]}"

