#!/usr/bin/env bash

while [[ $1 =~ ^- ]]; do
    case $1 in
        -h|--host)
            [ -n "$2" ] && LOKI_HOST=$2 || printf >&2 -- "'-h' Used but no host provided. Using default.\n";
            shift;
            shift;
            ;;
        -p|--port)
            [ -n "$2" ] && LOKI_PORT=$2 || printf >&2 -- "'-p' used but no port provided. Using default.\n";
            shift;
            shift;
            ;;
        -q|--query)
            [ -n "$2" ] && QUERY=$2 || printf >&2 -- "'-q' used but no query was provided. Using default.\n";
            shift;
            shift;
            ;;
        (-l|--limit)
            [ -n "$2" ] && LIMIT=$2 || printf >&2 -- "'-l' used but no limit was provided. Using default.\n";
            shift;
            shift;
            ;;
        (-j|--job)
            [ -n "$2" ] && QUERY="{job=\"$2\"}" || printf >&2 -- "'-j' used but no job name was provided.\n";
            shift;
            shift;
            ;;
        (-H|--help)
            printf "Hits the Loki query endpoint with the given query.\n"
            printf "The output is valid JSON.\n\n"
            printf -- "Usage: query_loki [ -h 192.168.4.53 ] [ -p 3100 ] [ -q '{job=\"all\"}' ] [ -l 10 ]\n"
            printf -- "Usage: query_loki [ -j \"all\" ] [ -l 10 ]\n\n"
            printf -- "Options:\n"
            printf -- "-j|--job\tSpecify the job to query.\n\n"
            printf -- "-q|--query\tSpecify the whole query to use. \n\t\tDefault query is '{job=\"all\"}'\n\n"
            printf -- "-l|--limit\tSpecify the limit to use. \n\t\tDefault limit is 10.\n\n"
            printf -- "-p|--port\tSpecify the port that Loki is using.\n\t\tDefault port is 3100.\n\n"
            printf -- "-h|--host\tSpecify the host (by IP) that is running Loki.\n\n"
            printf -- "-h|--help\tPrint this help message and exit.\n\n"
            printf "Tip: Pipe output through _jq_ to make it look nice.\n\n"
            printf "Ex.: query_loki -j 'all' | jq '.'\n"
            exit 0;
            ;;
        *)
            printf "No arguments given\n";
            ;;
    esac
done

: "${QUERY:="{job=\"all\"}"}"
: "${LIMIT:=10}"
: "${LOKI_HOST:=192.168.4.53}"
: "${LOKI_PORT:=3100}"
: "${LOKI_SERVER:="http://$LOKI_HOST:$LOKI_PORT"}"
: "${LOKI_QUERY_ENDPOINT:="$LOKI_SERVER/loki/api/v1/query_range"}"



curl "$LOKI_QUERY_ENDPOINT" \
    --data-urlencode "query=$QUERY" \
    --data-urlencode "limit=$LIMIT" # | jq -r '.streams[].entries[] | .line'

