#!/bin/bash
#===============================================================================
#
#          FILE:  admin-u16-s1
#
#         USAGE:  ./admin-u16-s1
#
#   DESCRIPTION:  This script sets up the first scenario for the unit 16 lab of 
#                 the ProLUG Linux admin course:
#                 https://professionallinuxusersgroup.github.io/lac/u16lab.html#scenario-1
#
#
#       OPTIONS:  There are currently no options for this script.
#  REQUIREMENTS:  Rocky Linux 9.x (dnf, rpm), bash >= 4.4
#        AUTHOR:  Connor W. (https://github.com/kolkhis)
#       CREATED:  2025-08-16
#
#===============================================================================

[[ $EUID -ne 0 ]] && {
    printf >&2 "ERROR: Script must be run with elevated privileges (root).\n"
    exit 1
}

declare -r HTTPD_CONFIG="/etc/httpd/conf/httpd.conf"

# Ensure httpd is installed and active
if ! rpm -qa | grep -qi "httpd"; then
    dnf install -y "httpd" || {
        printf >&2 "ERROR: Could not install the httpd package! \n"
        exit 1
    }
fi

if ! systemctl is-active httpd > /dev/null 2>&1; then 
    systemctl enable --now httpd || {
        printf >&2 "ERROR: Could not enable the httpd service!\n"
        exit 1
    }
fi

# Ensure firewall is installed and active. Block connections?
if ! rpm -qa | grep -qi 'firewalld'; then
    dnf install -y 'firewalld' || {
        printf >&2 "ERROR: Could not install the firewalld package!\n"
        exit 1
    }
fi

if ! systemctl is-active 'firewalld' > /dev/null 2>&1; then
    systemctl enable --now 'firewalld' || {
        printf >&2 "ERROR: Could not enable/start the firewalld service!\n"
        exit 1
    }
fi

# change the port for httpd server
if grep -Pqi '^Listen 80$' "${HTTPD_CONFIG}"; then 
    perl -pi -e 's/^(Listen) 80$/$1 8087/' "$HTTPD_CONFIG" || {
        printf >&2 "ERROR: Failed to change port to 8087 in %s\n" "$HTTPD_CONFIG"
        exit 1
    }
    systemctl restart httpd || {
        printf >&2 "ERROR: Could not restart the httpd service after changing port!\n"
        exit 1
    }
fi

printf -- "-- Lab successfully setup: Linux Admin Course - Unit 16, Scenario 1 --\n"
exit 0

