#!/bin/bash

declare HTTPD_CONFIG="/etc/httpd/conf/httpd.conf"

: "
This script sets up the first scenario:
https://professionallinuxusersgroup.github.io/lac/u16lab.html#scenario-1
"

# Ensure httpd is isntalled and active
if ! rpm -qa | grep -qi "httpd"; then
    dnf install -y "httpd" || {
        printf >&2 "ERROR: Could not install the httpd package! \n"
        exit 1
    }
fi

if ! systemctl is-active httpd; then 
    systemctl enable --now httpd || {
        printf >&2 "ERROR: Could not enable the httpd service!\n"
        exit 1
    }
fi

# Ensure firewall is installed and active. Block connections?
if ! rpm -qa | grep -qi 'firewalld'; then
    dnf install -y 'firewalld' || {
        printf >&2 "ERROR: Could not install the firewalld package!\n"
        exit 1
    }
fi

if ! systemctl is-active 'firewalld'; then
    systemctl enable --now 'firewalld' || {
        printf >&2 "ERROR: Could not enable/start the firewalld service!\n"
        exit 1
    }
fi


# change the port for httpd server
if grep -Pi '^Listen 80$' "${HTTPD_CONFIG}"; then 
    perl -pi -e 's/^(Listen) 80$/\1 8087/' "$HTTPD_CONFIG" || {
        printf >&2 "ERROR: Failed to change port to 8087 in %s\n" "$HTTPD_CONFIG"
        exit 1
    }
    systemctl restart httpd || {
        printf >&2 "ERROR: Could not restart the httpd service after changing port!\n"
        exit 1
    }
fi

printf ">> Lab setup for scenario 1 of Linux Admin Course unit 16\n"

exit 0

