#!/bin/bash


declare INVENTORY_FILE
declare KNOWN_HOSTS="$HOME/.ssh/known_hosts"
declare -a IPS

process-inventory(){
    for entry in "${ENTRIES[@]}"; do
        local parsed_ip=
        parsed_ip="$(perl -ne 'print $1 if m/\b(\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})\b/' <<< "$entry")"
        { [[ -n $parsed_ip ]] && IPS=("${IPS[@]}" "$parsed_ip"); } || continue
    done
}

add-fingerprints(){
    local fingerprint_file
    fingerprint_file="$(mktemp)"
    for ip in "${IPS[@]}"; do
        printf "Checking for fingerprint for %s...\n" "$ip"
        : > "$fingerprint_file"

        ssh-keyscan -H "$ip" 2>/dev/null | grep -o '^|.*$' > "$fingerprint_file" || {
            printf >&2 "Failed to obtain fingerprint from: %s\n" "$ip" && continue
        }
        if ! ssh-keygen -F "$ip" -f "$KNOWN_HOSTS" > /dev/null 2>&1; then
            printf "Fingerprint not found. Adding...\n"
            cat -s "$fingerprint_file" | tee -a "$KNOWN_HOSTS" > /dev/null 2>&1 || {
                printf >&2 "Failed to add fingerprint for %s to %s\n" "$ip" "$KNOWN_HOSTS" && return 1
            }
        else
            printf "Fingerprint for %s already exists in %s -- skipping.\n" "$ip" "$KNOWN_HOSTS"
            continue
        fi

    done

}


while [[ -n $1 && $1 =~ ^- && $1 != '--' ]]; do
    case $1 in
        -i|--inventory)
            { [[ -n $2 && ! $2 =~ ^- ]] && shift && INVENTORY_FILE=$1; } || {
                printf >&2 "Bad argument to -i/--inventory: %s\n" "$2"
            }
            shift;
            ;;

        -k|--known-hosts)
            { [[ -n $2 && ! $2 =~ ^- ]] && shift && KNOWN_HOSTS=$1; } || {
                printf >&2 "Bad argument to -i/--inventory: %s\n" "$2"
            }
            shift;
            ;;
        *)
            ;;
    esac
done

INVENTORY_FILE="${INVENTORY_FILE:?No inventory file was provided! Run again with --help for usage.}"

declare -a ENTRIES
mapfile -t ENTRIES < "$INVENTORY_FILE"

process-inventory || {
    printf >&2 "Failed to process inventory! \n" && exit 1
}

printf "Inventory processed.\n"
printf "IP Address list obtained:\n"
printf -- "- %s\n" "${IPS[@]}"

add-fingerprints || {
    printf >&2 "Failed to add fingerprints to known hosts file! (%s)\n" "$KNOWN_HOSTS" && exit 1
}
printf "Fingerprints successfully added!\n" && exit 0


