#!/bin/bash
# Wrapper script for cluster initialization with `kubeadm init`

declare -r POD_NETWORK_CIDR="10.244.0.0/16"

# Cleanup
[[ -f ~/.kube/config ]] && {
    printf "Cleaning up old kube config file...\n"
    sudo rm -f ~/.kube/config
} 

[[ -d ~/.kube/cache ]] && {
    printf "Cleaning up old kube config cache directory...\n"
    sudo rm -rf ~/.kube/cache
}

printf "Initializing cluster with kubeadm...\n"
sudo kubeadm init \
    --pod-network-cidr="$POD_NETWORK_CIDR" \
    --cri-socket=unix:///run/containerd/containerd.sock \
    --skip-phases=addon/kube-proxy || {
    printf >&2 "There was a problem initializing the cluster with 'kubeadm init'!\n" && exit 1
}

printf "Creating kube config directory and copying admin.conf\n"
{ 
    mkdir -p ~/.kube 
    sudo cp -i /etc/kubernetes/admin.conf "$HOME/.kube/config"
    sudo chown "$(id -u):$(id -g)" "$HOME/.kube/config"; 
} || {
    printf >&2 "Problem with kube config directory ~/.kube\n" && exit 1
}
printf "Done.\n"

