#!/bin/bash
# Wrapper script for cluster initialization with `kubeadm init`
# Removes ~/.kube/config and ~/.kube/cache (if present) unless `-n`/`--no-cleanup` is passed.

declare POD_NETWORK_CIDR="10.244.0.0/16"
declare CLEANUP=0

while [[ -n $1 && $1 =~ ^- ]]; do
    case $1 in
        -n|-no-cleanup|--no-cleanup)
            printf "Skipping cleanup.\n"
            CLEANUP=1
            shift
            ;;
        -p|-pod-network|--pod-network)
            if [[ -n $2 && ! $2 =~ ^- ]]; then
                shift
                printf "Setting pod network CIDR to: %s\n" "$1"
            else
                printf >&2 "[ERROR]: Bad or missing argument to -p|--pod-network.\n"
                exit 1
            fi
            shift
            ;;
        *)
            printf >&2 "[ERROR]: Unknown argument, exiting: %s\n" "$1"
            exit 1
            ;;
    esac
done

# Cleanup
cleanup(){
    if [[ -f ~/.kube/config ]]; then
        printf "Cleaning up old kube config file...\n"
        sudo rm -f ~/.kube/config
    fi

    if [[ -d ~/.kube/cache ]]; then
        printf "Cleaning up old kube config cache directory...\n"
        sudo rm -rf ~/.kube/cache
    fi
}

[[ $CLEANUP -gt 0 ]] && cleanup


printf "Initializing cluster with kubeadm...\n"
sudo kubeadm init \
    --pod-network-cidr="$POD_NETWORK_CIDR" \
    --cri-socket=unix:///run/containerd/containerd.sock \
    --skip-phases=addon/kube-proxy || {
    printf >&2 "There was a problem initializing the cluster with 'kubeadm init'!\n" && exit 1
}

printf "Creating kube config directory and copying admin.conf\n"
{ 
    mkdir -p ~/.kube 
    sudo cp -i /etc/kubernetes/admin.conf "$HOME/.kube/config"
    sudo chown "$(id -u):$(id -g)" "$HOME/.kube/config"; 
} || {
    printf >&2 "Problem with kube config directory ~/.kube\n" && exit 1
}
printf "Done.\n"

