#!/bin/bash
# Installer script for Cilium. 
# Run only on your k8s control node.  
# Cilium only needs to be installed on the master node. As a safety mechanism, 
# this script will not install Cilium if the local hostname does not contain 
# the word 'control' or 'master'. This is to prevent accidental installation on
# worker nodes or load balancer nodes.

declare -r CILIUM_DOWNLOAD_LINK='https://github.com/cilium/cilium-cli/releases/latest/download/cilium-linux-amd64.tar.gz'
declare -r CILIUM_TARBALL="${CILIUM_DOWNLOAD_LINK##*/}"
declare -r TMP_INSTALL_DIR="/tmp/cilium-install"

declare -i IGNORE_HOSTNAME=0

while [[ -n $1 && $1 =~ ^- && $1 != '--' ]]; do
    case $1 in
        -i|--ignore-hostname)
            ;;
        *)
            IGNORE_HOSTNAME=1
            ;;
    esac
done

install-cilium() {

    printf "Creating temporary install directory...\n"
    mkdir -p "$TMP_INSTALL_DIR" || {
        printf >&2 "Unable to create temporary directory: %s\n" "$TMP_INSTALL_DIR" && return 1
    }

    cd "$TMP_INSTALL_DIR" || {
        printf >&2 "Couldn't switch to directory: %s\n" "$TMP_INSTALL_DIR" && return 1
    }

    printf "Downloading Cilium tarball...\n"
    curl -LO "$CILIUM_DOWNLOAD_LINK" || {
        printf >&2 "Problem downloading cilium tarball.\n" && return 1
    }

    printf "Extracting tarball...\n"
    tar -xzvf "$TMP_INSTALL_DIR/$CILIUM_TARBALL" || {
        printf >&2 "Problem extracting cilium tarball.\n" && return 1
    }

    printf "Copying Cilum binary to /usr/local/bin..."
    sudo cp "$TMP_INSTALL_DIR/cilium" /usr/local/bin || {
        printf >&2 "Problem copying cilium binary to /usr/local/bin\n" && return 1
    }

    printf "Cleaning up installation files...\n"
    rm -rf "$TMP_INSTALL_DIR" || {
        printf >&2 "Failed to remove cilium install directory.\n" && return 1
    }

    printf "Verifying installation...\n"
    { [[ -x /usr/local/bin/cilium ]] && command -v cilium > /dev/null 2>&1; } && {
        printf "Successfully installed and added Cilium to PATH.\n"
        return 0
    }
    return 1

}

if [[ $IGNORE_HOSTNAME -gt 0 ]]; then
    case $HOSTNAME in
        *control*|*master*)
            printf "On master/control node. Installing cilium...\n"
            if ! install-cilium; then
                printf >&2 "Problem installing cilium.\n" && exit 1
            fi
            ;;
        *worker*)
            printf "Cilium only needs to be installed on the master/control node!\n"
            exit 0
            ;;
        *)
            printf "Hostname does not reflect a k8s worker or control node. Exiting.\n"
            exit 0
            ;;
    esac
fi

