#!/bin/bash

# Switched to process substitution for loop redirect
# Fixed redirection error on connection check, handle bad connection gracefully
# Changed some syntax
# Added colors and formatting to user, platform, and answers to make things stand out more

# Directory to watch
WATCH_FILE="/data/stream_write/stream_answers"

# Watch for events (create, modify, delete, etc.)
while read -r event; do

    # Show the command entry
    user="\033[32m$(tail -n1 "$WATCH_FILE" | awk -F: '{print $1}')\033[0m"
    source="\033[32m$(tail -n1 "$WATCH_FILE" | awk -F: '{print $2}')\033[0m"
    command="$(tail -n1 "$WATCH_FILE" | awk -F: '{print $NF}')"

    # Make the command stand out a bit more
    printf "User: %s answered on %s. Their command is:\n\t%s" \
        "$user" "$source" "\033[33m$command\033[0m"

    # Select a server to use
    num=$(( (RANDOM % 5) + 15 ))
    printf "Using rocky%s\n" "$num"

    sleep 2

    # Execute the command
    if ! ping -c 1 rocky$num > /dev/null 2>&1; then
        printf "The server 'rocky%s' is unreachable!\n" "$num"
        continue
    fi
    timeout 10 ssh -i /root/.ssh/cluster_key rocky$num "$command"

done < <(inotifywait -m -r -e create,modify,delete "$WATCH_FILE")

