#!/bin/bash

declare -i NEEDS_REBOOT=0

reboot-if-needed(){
    [[ $NEEDS_REBOOT -gt 0 ]] || return 0
    local current_time
    printf -v current_time "%(%F %T)T"
    wall "Timeout Limit Reached for user. Rebooting lab machine now: $current_time"
    # exec reboot
}

get-idle-time() {
    local idle_time
    local -i hours_idle

    idle_time="$(/usr/bin/who -u | awk '/^root\s*pts\/0/ {print $5}')"
    
    printf "Idle time: %s\n" "$idle_time"

    if [[ "$idle_time" == '.' ]]; then
        # Last command was run in the last 60 seconds
        NEEDS_REBOOT=0
    elif [[ "$idle_time" == 'old' ]]; then
        # Last cmd was run >= 24hrs ago
        NEEDS_REBOOT=1
    else
        # Last cmd was run HH:MM ago
        hours_idle="${idle_time%%:*}"
        [[ $hours_idle -gt 8 ]] && NEEDS_REBOOT=1
    fi
}

get-idle-time
reboot-if-needed


