#!/bin/bash
# Create a VM template that is cloud-init ready for Proxmox VE
# Written by Connor W. (https://github.com/kolkhis)

err() {
    if [[ $# -gt 0 ]]; then
        printf >&2 '[\033[31mERROR\033[0m]: %s\n' "$*"
    else
        printf >&2 '[\033[31mERROR\033[0m]: '
    fi
}

if [[ $EUID -ne 0 ]]; then
    err 'Run as root.'
    exit 1
fi

create-rocky10-template(){
    local -i vmid=9030
    local -i mem=2048
    local -i cores=1
    local -i sockets=1
    local storage_pool="vmdata"
    local template_name="rocky-10-cloudinit-template"
    local template_image="/var/lib/vz/template/qcow/Rocky-10-GenericCloud-Base.latest.x86_64.qcow2"
    local cputype="host"

    if ! [[ -f $template_image ]]; then
        err "Template image does not exist: $template_image"
        return 1
    fi

    qm create "$vmid" \
        --name "$template_name" \
        --memory "$mem" \
        --cpu "$cputype" \
        --cores "$cores" \
        --sockets "$sockets" \
        --storage "$storage_pool" \
        --net0 virtio,bridge=vmbr0 \
        --machine q35 \
        --bios ovmf || {
            err '[ERROR]: Initial VM creation failed.'
            return 1
        }

    qm disk import "$vmid" "$template_image" "$storage_pool"

    qm set "$vmid" --scsihw virtio-scsi-pci --scsi0 "$storage_pool:vm-$vmid-disk-0"
    qm set "$vmid" --efidisk0 "$storage_pool:0,format=raw,efitype=4m"
    qm set "$vmid" --ide2 "$storage_pool:cloudinit"
    qm set "$vmid" --agent enabled=1
    qm set "$vmid" --boot order=scsi0

    printf "[INFO]: Successfully created the base image.\n" 
    printf "[INFO]: Convert new VM to a template when ready by running: qm template %d\n" "$vmid"
}

create-rocky10-template || {
    err "Failed to create Rocky 10 template."
    exit 1
}

printf "[INFO]: Template created.\n"
exit 0


