#!/bin/bash
# shellcheck disable=SC2120
# Create a VM template that is cloud-init ready for Proxmox VE
# Written by Connor W. (https://github.com/kolkhis)

err() {
    if [[ $# -gt 0 ]]; then
        printf >&2 '[\033[31mERROR\033[0m]: %s\n' "$*"
    else
        printf >&2 '[\033[31mERROR\033[0m]: '
    fi
}

if [[ $EUID -ne 0 ]]; then
    err 'Run as root.'
    exit 1
fi

declare TEMPLATE_IMAGE="/var/lib/vz/template/qcow/Rocky-10-GenericCloud-Base.latest.x86_64.qcow2"
declare TEMPLATE_NAME="/var/lib/vz/template/qcow/Rocky-10-GenericCloud-Base.latest.x86_64.qcow2"
declare -i VMID=100

while [[ -n $1 && $1 =~ ^- ]]; do
    [[ $1 == '--' ]] && break
    case $1 in
        -i|--image)
            if [[ -n $2 && ! $2 =~ ^- && -f $2 ]]; then
                shift
                TEMPLATE_IMAGE="$1"
            else
                err 'Bad or missing argument to -i|--image.'
                exit 1
            fi
            shift;
            ;;
        -n|--name)
            if [[ -n $2 && ! $2 =~ ^- ]]; then
                shift
                TEMPLATE_NAME="$1"
            fi
            shift
            ;;
        -v|--vmid)
            if [[ -n $2 && ! $2 =~ ^- ]]; then
                shift
                VMID="$2"
            fi
            shift
            ;;
        *)
            ;;
    esac
done

create-uefiboot-template(){
    local -i vmid=9030
    local -i mem=2048
    local -i cores=1
    local -i sockets=1
    local storage_pool="vmdata"
    local template_name="rocky-10-cloudinit-template"
    local template_image="/var/lib/vz/template/qcow/Rocky-10-GenericCloud-Base.latest.x86_64.qcow2"
    local cputype="host"

    while [[ -n $1 && $1 =~ ^- ]]; do
        case $1 in
            -i|--image) 
                [[ -n $2 && -f $2 ]] && shift && template_image="$1"
                shift
                ;;
            -n|--name)
                [[ -n $2 ]] && shift && template_name="$1"
                ;;
            -v|--vmid)
                [[ -n $2 ]] && shift && vmid="$1"
                shift
                ;;
        esac
    done

    if ! [[ -f $template_image ]]; then
        err "Template image does not exist: $template_image"
        return 1
    fi

    qm create "$vmid" \
        --name "$template_name" \
        --memory "$mem" \
        --cpu "$cputype" \
        --cores "$cores" \
        --sockets "$sockets" \
        --storage "$storage_pool" \
        --net0 virtio,bridge=vmbr0 \
        --machine q35 \
        --bios ovmf || {
            err 'Initial VM creation failed.'
            return 1
        }

    qm disk import "$vmid" "$template_image" "$storage_pool"

    qm set "$vmid" --scsihw virtio-scsi-pci --scsi0 "$storage_pool:vm-$vmid-disk-0"
    qm set "$vmid" --efidisk0 "$storage_pool:0,format=raw,efitype=4m"
    qm set "$vmid" --ide2 "$storage_pool:cloudinit"
    qm set "$vmid" --agent enabled=1
    qm set "$vmid" --boot order=scsi0

    printf "[INFO]: Successfully created the base image.\n" 
    printf "[INFO]: Convert new VM to a template when ready by running: qm template %d\n" "$vmid"
}

create-uefiboot-template -i "$TEMPLATE_IMAGE" -n "$TEMPLATE_NAME" -v "$VMID" || {
    err "Failed to create Proxmox template."
    exit 1
}

printf "[INFO]: Template successfully created.\n"
exit 0


