#!/bin/bash
# shellcheck disable=SC2120
# Create a VM template that is cloud-init ready for Proxmox VE
# Written by Connor W. (https://github.com/kolkhis)

usage() {
        cat <<EOF
Usage: ${BASH_SOURCE[0]} [OPTIONS]

Create a Proxmox VM template that is Cloud-Init ready.
Defaults are chosen to work on most Proxmox installations.

OPTIONS:
  -i, --image <file>       Path to the QCOW2 cloud image to import.
                           Default: $TEMPLATE_IMAGE

  -s, --storage <name>     Proxmox storage target for disks.
                           Default: $STORAGE

  -n, --name <string>      Name of the VM template to create.
                           Default: $TEMPLATE_NAME

  -v, --vmid <number>      Proxmox VMID for the new VM.
                           Default: $VMID

  -m, --memory <MiB>       Amount of RAM (in MiB).
                           Default: $MEM

  -c, --cores <number>     Number of CPU cores assigned.
                           Default: $CORES

  -S, --sockets <number>   Number of CPU sockets assigned.
                           Default: $SOCKETS

  -t, --cpu-type <string>  Proxmox CPU type (e.g., host, x86-64-v2-AES).
                           Default: $CPU_TYPE

  -h, --help               Show this help message and exit.

NOTES:
  - Requires root privileges.
  - After creation, convert the VM into a template using:
        qm template <vmid>

EXAMPLE:
  ${BASH_SOURCE[0]} --image /path/to/cloud-image.qcow2 --vmid 900 --name rocky-ci-template

EOF
}

err() {
    if [[ $# -gt 0 ]]; then
        printf >&2 '[\033[31mERROR\033[0m]: %s\n' "$*"
    else
        printf >&2 '[\033[31mERROR\033[0m]: '
    fi
}

if [[ $EUID -ne 0 ]]; then
    err 'Run as root.'
    exit 1
fi

declare TEMPLATE_IMAGE="/var/lib/vz/template/qcow/Rocky-10-GenericCloud-Base.latest.x86_64.qcow2"
declare TEMPLATE_NAME="rocky10-cloudinit-template"
declare STORAGE="vmdata"
declare -i VMID=100
declare -i MEM=2048
declare -i CORES=1
declare -i SOCKETS=1
declare CPU_TYPE='host'

while [[ -n $1 && $1 =~ ^- ]]; do
    [[ $1 == '--' ]] && break
    case $1 in
        -i|--image)
            if [[ -n $2 && ! $2 =~ ^- && -f $2 ]]; then
                shift
                TEMPLATE_IMAGE="$1"
            else err 'Bad or missing argument to -i|--image. Does the image file exist?' && exit 1; fi
            shift;
            ;;

        -s|--storage)
            if [[ -n $2 && ! $2 =~ ^- ]]; then
                shift
                STORAGE="$1"
            else err 'Bad or missing argument to -s|--storage.' && exit 1; fi
            shift
            ;;

        -n|--name)
            if [[ -n $2 && ! $2 =~ ^- ]]; then
                shift
                TEMPLATE_NAME="$1"
            else err 'Bad or missing argument to -n|--name.' && exit 1; fi
            shift
            ;;

        -v|--vmid)
            if [[ -n $2 && ! $2 =~ ^- ]]; then
                shift
                VMID="$1"
            else err 'Bad or missing argument to -v|--vmid.' && exit 1; fi
            shift
            ;;

        -m|--memory)
            if [[ -n $2 && ! $2 =~ ^- ]]; then
                shift
                MEM=$1
            else err 'Bad or missing argument to -m|--memory.' && exit 1; fi
            shift
            ;;

        -c|--cores)
            if [[ -n $2 && ! $2 =~ ^- ]]; then
                shift
                CORES=$1
            else err 'Bad or missing argument to -c|--cores.' && exit 1; fi
            shift
            ;;

        -S|--sockets)
            if [[ -n $2 && ! $2 =~ ^- ]]; then
                shift
                SOCKETS=$1
            else err 'Bad or missing argument to -S|--sockets.' && exit 1; fi
            shift
            ;;

        -t|--cpu-type)
            if [[ -n $2 && ! $2 =~ ^- ]]; then
                shift
                CPU_TYPE=$1
            else err 'Bad or missing argument to -t|--cpu-type.' && exit 1; fi
            shift
            ;;
        -h|-help|--help)
            usage
            exit 0
            ;;
        *)
            err "Unknown argument given: $1"
            exit 1
            ;;

    esac
done

[[ -n $1 && $1 == '--' ]] && shift

create-uefiboot-template(){

    if ! [[ -f $TEMPLATE_IMAGE ]]; then
        err "Template image does not exist: $TEMPLATE_IMAGE" && return 1
    fi

    qm create "$VMID" \
        --name "$TEMPLATE_NAME" \
        --memory "$MEM" \
        --cpu "$CPU_TYPE" \
        --cores "$CORES" \
        --sockets "$SOCKETS" \
        --storage "$STORAGE" \
        --net0 virtio,bridge=vmbr0 \
        --machine q35 \
        --bios ovmf || {
            err 'Initial VM creation failed.' && return 1
        }

    qm disk import "$VMID" "$TEMPLATE_IMAGE" "$STORAGE"

    qm set "$VMID" --scsihw virtio-scsi-pci --scsi0 "$STORAGE:vm-$VMID-disk-0"
    qm set "$VMID" --efidisk0 "$STORAGE:0,format=raw,efitype=4m"
    qm set "$VMID" --ide2 "$STORAGE:cloudinit"
    qm set "$VMID" --agent enabled=1
    qm set "$VMID" --boot order=scsi0

    printf "[INFO]: Successfully created the base image.\n" 
    printf "[INFO]: Convert new VM to a template when ready by running: qm template %d\n" "$vmid"
}

create-uefiboot-template || {
    err "Failed to create Proxmox template."
    exit 1
}

printf "[INFO]: Template successfully created.\n"
exit 0


