#!/bin/bash

declare LOGFILE="./zfs-check.log"
declare -i MAX_ALLOWED_USAGE=70

declare -a POOLS
declare -a STORAGE_PROBLEM
declare -a ERROR_PROBLEM

read -r -d '' -a POOLS < <(zpool list -H -o name)

for pool in "${POOLS[@]}"; do
    errors="$(zpool status "$pool" | tail -n 1)"
    usage="$(zpool list -H -o capacity vmdata)"

    if [[ $errors != "errors: No known data errors" ]]; then
        printf "[WARNING]: Errors found in pool: %s\n" "$pool"
        ERROR_PROBLEM=("${ERROR_PROBLEM[@]}" "$pool")
    fi

    if [[ ${usage%%%} -gt "$MAX_ALLOWED_USAGE" ]]; then
        printf "[WARNING]: Storage utilization exceeds max allowed usage. Usage: %s\n" "$usage"
        STORAGE_PROBLEM=("${STORAGE_PROBLEM[@]}" "$pool")
    fi

done


if [[ ${#ERROR_PROBLEM[@]} -gt 0 ]]; then
    printf "%(%F %T)T [ERROR]: Problematic pools found (errors):\n" >> "$LOGFILE"
    printf "\t%s\n" "${ERROR_PROBLEM[@]}" >> "$LOGFILE"
fi

if [[ ${#STORAGE_PROBLEM[@]} -gt 0 ]]; then
    printf "%(%F %T)T [ERROR]: Problematic pools found (storage saturation):\n" >> "$LOGFILE"
    printf "\t%s\n" "${STORAGE_PROBLEM[@]}" >> "$LOGFILE"
fi


