---
- name: Make a sudoers group for clean rocky installations then add user to suoders
  # Caveat: Need sudo access to create sudoers. Can't SSH as root without key auth
  hosts: rocky
  become: true
  vars:
    primary_user: kolkhis
    users:
      - kolkhis
    sudo_group_line: "%sudo ALL=(ALL:ALL) ALL"
    rc_lines:
      - set -o vi
      - alias lv="vi -c \"normal '0\""
  tasks:

    - name: Add sudo group, and add users to sudo
      block: 
        - name: Create the sudo group
          ansible.builtin.group:
            name: sudo
            state: present

        - name: Check for sudoers group in /etc/sudoers
          ansible.builtin.lineinfile:
            path: /etc/sudoers
            regexp: |
              ^%sudo\s+ALL=\(ALL(:ALL)?\)\s+ALL
            line: "{{ sudo_group_line }}"  # will be added if regex doesn't match
          register: line_info

        - name: Debug the output of lineinfile
          ansible.builtin.debug:
            msg: "Output: {{ line_info }}"

        - name: Add user to the sudoers group
          ansible.builtin.user:
            name: "{{ item }}"
            groups:
              - sudo
            state: present
          loop: "{{ users }}"
      rescue:
        - name: Debug failure
          ansible.builtin.debug:
            msg: "Couldn't create sudoers group."

    - name: Set up environment to be comfortable
      block:
        - name: Set personal shell options in user's bashrc
          ansible.builtin.lineinfile:
            path: "/home/{{ primary_user }}/.bashrc"
            line: "{{ item }}"
            regex: "^{{ item }}"
            state: present
          loop: "{{ rc_lines }}"

        - name: Set personal shell options in root's bashrc
          ansible.builtin.lineinfile:
            path: /root/.bashrc
            line: "{{ item }}"
            regex: "^{{ item }}"
            state: present
          loop: "{{ rc_lines }}"

    - name: Clone scripts repo to local machine
      ansible.builtin.git:
        repo: "https://github.com/kolkhis/scripts-playbooks.git"
        dest: /home/kolkhis/
