#!/bin/bash
# Create a VM template that is cloud-init ready

create-template-virtio(){
    local -i vmid=9030
    local -i mem=2048
    local -i cores=1
    local -i sockets=1
    local storage_pool="vmdata"
    local template_name="rocky-10-cloudinit-template"
    local template_image="/var/lib/vz/template/qcow/Rocky-10-GenericCloud-Base.latest.x86_64.qcow2"
    local cputype="x86-64-v2-AES"


    qm create "$vmid" \
        --name "$template_name" \
        --memory "$mem" \
        --cpu "$cputype" \
        --cores "$cores" \
        --sockets "$sockets" \
        --storage "$storage_pool" \
        --net0 virtio,bridge=vmbr0 \
        --machine q35 \
        --bios ovmf

    qm disk import "$vmid" "$template_image" "$storage_pool"
    qm set "$vmid" --scsihw virtio-scsi-pci --scsi0 "$storage_pool:vm-$vmid-disk-0"
    qm set "$vmid" --efidisk0 "$storage_pool:0,format=raw,efitype=4m"
    qm set "$vmid" --ide2 "$storage_pool:cloudinit"
    qm set "$vmid" --agent enabled=1
    qm set "$vmid" --boot order=scsi0


    printf "Created the base image.\n" 
    printf "Convert to a template when ready by running: qm template %d\n" "$vmid"
}

create-template-virtio


# declare VM_STORAGE_LOCATION="${STORAGE_POOL}:vm-$VMID-disk-0"
# declare CI_USER='luser'
# declare CI_PASS='luser'
# declare CLOUD_TEMPLATE='/var/lib/vz/template/qcow/Rocky-10-GenericCloud-Base.latest.x86_64.qcow2'
# declare CPU_TYPE='x86-64-v2-AES'
# declare TEMPLATE_NAME='rocky9-gencloud-template'
# declare -i VMID=9000
# declare -i MEM=2048
# declare -i CORES=1
# declare -i SOCKETS=1
# declare STORAGE_POOL='vmdata'

# qm create "$VMID" --name "$TEMPLATE_NAME" \
#     --memory "$MEM" \
#     --net0 virtio,bridge=vmbr0 \
#     --cores "$CORES" \
#     --sockets "$SOCKETS" \
#     --cpu "$CPU_TYPE" \
#     --storage "$STORAGE_POOL"

# Create config file if it doesn't exist
# touch "/etc/pve/qemu-server/$VMID.conf"

# qm importdisk "$VMID" "$CLOUD_TEMPLATE" "$STORAGE_POOL"
# qm set "$VMID" --virtio0 "$VM_STORAGE_LOCATION"
# qm set "$VMID" --boot c --bootdisk virtio0
# qm set "$VMID" --ide2 "${STORAGE}:cloudinit"
# qm set "$VMID" --ciuser "$CI_USER" --cipassword "$CI_PASS"
# qm set "$VMID" --agent 1


# qm set 9020 --scsi0 vmdata:0,import-from=/var/lib/vz/template/qcow/Rocky-10-GenericCloud-Base.latest.x86_64.qcow2
# qm set "$VMID" --scsi0 "${STORAGE_POOL}:0,import-from=${CLOUD_TEMPLATE}"

