#!/bin/bash
# shellcheck disable=
declare VALUE

if [[ $# == 0 ]]
then
        read -p "Enter a default value : " VALUE
        printf "The default value is : %s\n" "$VALUE"
        exit 0
fi


while [[ -n $1 ]]
do
        if [[ ! $1 =~ ^- ]]; then printf "This is not a flag.\n";shift;fi
        case $1 in
                -h|--help)
                        printf "This is the help for the script.\n"
                        shift
                        ;;
                -s|--set)
                        if [[ $2 =~ ^- ]]
                        then
                                printf "This should be a value.\n"
                                exit 1
                        else
                                printf "The value is %s\n" "$2"
                                shift
                                shift
                        fi
                        ;;
                *)
                        printf "Unknown flags.\n"
                        shift
                        ;;
        esac
done


