#!/bin/bash

declare CHROOT_DIR='/var/chroot'
declare JAILED_USER='juvie'

# declare -a BINARIES
# BINARIES=("bash" "rbash" "ssh")

# declare -a SYSFILES
# SYSFILES=("/etc/passwd" "/etc/group" "/etc/nsswitch.conf" "/etc/hosts")

setup-chroot-dir() {
    local -a BINARIES
    BINARIES=("bash" "rbash" "ssh")
    local -a SYSFILES
    SYSFILES=("/etc/passwd" "/etc/group" "/etc/nsswitch.conf" "/etc/hosts")
    local ALL_LLIBS

    for BINARY in "${BINARIES[@]}"; do
        local -a BIN_LLIBS
        # Gather Link Libraries for the binary
        IFS=$'\n' read -r -d '' -a BIN_LLIBS < <(ldd "$(which "$BINARY")" |
            perl -ne 'print $1 . "\n" if s/^[^\/]*(\/.*)\(.*$/\1/')

        printf "Binary: %s\n" "${BINARY}"
        printf "LLIB: %s\n" "${BIN_LLIBS[@]}"
        for LLIB in "${BIN_LLIBS[@]}"; do
            cp "${LLIB}" "${CHROOT_DIR}/${LLIB}"
        done
    done

    # printf "LLIBs:\n" 
    # printf "%s\n" "${ALL_LLIBS[@]}"
    # printf "Total number of Link Libraries: %s\n" "${#ALL_LLIBS[@]}"


    printf "Setting up chroot jail environment.\n"
    # [[ ! -d /var/chroot ]] && sudo mkdir -p /var/chroot
    
    for SYSFILE in "${SYSFILES[@]}"; do
        printf "Copying system file: %s\n" "$SYSFILE"
        # cp "$SYSFILE" "$CHROOT_DIR/$SYSFILE"
    done

    # extract only paths
    for LLIB in $(ldd /bin/bash | perl -ne 'print $1 . "\n" if s/^[^\/]*(\/.*)\(.*$/\1/'); do
        # cp "$LLIB" "/var/chroot/$LLIB"
        :
    done 

}

setup-chroot-dir
